services:
    oro_email.tests.emailtemplate.variable_provider:
        class: Oro\Bundle\EmailBundle\Tests\Functional\Environment\TestEntityVariablesProvider
        public: false
        tags:
            - { name: oro_email.emailtemplate.variable_provider, scope: entity }

    oro_email.tests.emailtemplate.variable_processor:
        class: Oro\Bundle\EmailBundle\Tests\Functional\Environment\TestVariableProcessor
        public: false
        tags:
            - { name: oro_email.emailtemplate.variable_processor, alias: tests.processor }
