hwi_oauth:
    firewall_names: [main]

security:
    firewalls:
        main:
            oauth:
                login_path: oro_user_security_login
                failure_path: oro_user_security_login
                check_path: oro_user_security_check
                oauth_user_provider:
                    service: oro_sso.oauth_user_provider
