services:
    oro_test_generator.generator.test.abstract:
        abstract: true
        arguments:
            - '@twig'
            - '@kernel'

    oro_test_generator.generator.test.unit:
        parent: oro_test_generator.generator.test.abstract
        class: Oro\Bundle\TestGeneratorBundle\Generator\UnitTestGenerator

    oro_test_generator.generator.test.entity:
        parent: oro_test_generator.generator.test.abstract
        class: Oro\Bundle\TestGeneratorBundle\Generator\EntityTestGenerator

    oro_test_generator.generator.test.functional:
        parent: oro_test_generator.generator.test.abstract
        class: Oro\Bundle\TestGeneratorBundle\Generator\FunctionalTestGenerator

    oro_test_generator.test_type_service_locator:
        class: Symfony\Component\DependencyInjection\ServiceLocator
        arguments:
            -
                oro_test_generator.generator.test.unit: '@oro_test_generator.generator.test.unit'
                oro_test_generator.generator.test.entity: '@oro_test_generator.generator.test.entity'
                oro_test_generator.generator.test.functional: '@oro_test_generator.generator.test.functional'
        tags:
            - { name: container.service_locator }
