Oro\Bundle\IntegrationBundle\Entity\Channel:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
            fields: [name, organization]
    properties:
        name:
            - NotBlank: ~
            - Length:
                min: 3
                max: 255
        type:
            - NotBlank: ~
        organization:
            - NotBlank: ~
