services:
    oro_action.configuration.provider:
        class: Oro\Bundle\ActionBundle\Configuration\ConfigurationProvider
        public: false
        parent: oro.static_config_provider.abstract
        arguments:
            - '%kernel.cache_dir%/oro/actions.php'
            - '%kernel.debug%'
            - '@service_container'
            - '%kernel.bundles%'

    oro_action.configuration.validator.action_group:
        class: Oro\Bundle\ActionBundle\Configuration\ActionGroupConfigurationValidator

    oro_action.configuration.validator.operations:
        class: Oro\Bundle\ActionBundle\Configuration\OperationConfigurationValidator
        arguments:
            - '@oro_ui.controller_class_provider'
            - '@twig.loader'
            - '@oro_entity.doctrine_helper'
            - '@logger'
            - '%kernel.debug%'

    oro_action.configuration.provider.operations:
        class: Oro\Bundle\ActionBundle\Configuration\SectionConfigurationProvider
        arguments:
            - '@oro_action.configuration.provider'
            - 'operations'

    oro_action.configuration.provider.action_groups:
        class: Oro\Bundle\ActionBundle\Configuration\SectionConfigurationProvider
        arguments:
            - '@oro_action.configuration.provider'
            - 'action_groups'

    oro_action.configuration_pass.replace_property_path:
        class: Oro\Component\ConfigExpression\ConfigurationPass\ReplacePropertyPath
        arguments:
            - "data"

    oro_action.config_extension.feature:
        class: Oro\Bundle\ActionBundle\Configuration\FeatureConfigurationExtension
        tags:
            - { name: oro_feature.config_extension }
