parameters:
    translator.class: Oro\Bundle\TranslationBundle\Translation\Translator

services:
    oro_translation.controller:
        class: Oro\Bundle\TranslationBundle\Controller\Controller
        public: true
        arguments:
            - '@translator.default'
            - '@templating'
            - OroTranslationBundle:Translation:translation.js.twig
            - ""
        lazy: true

    Oro\Bundle\TranslationBundle\Download\TranslationDownloader:
        arguments:
            - '@Oro\Bundle\TranslationBundle\Download\OroTranslationServiceAdapter'
            - '@Oro\Bundle\TranslationBundle\Download\CachingTranslationMetricsProvider'
            - '@oro_translation.js_dumper'
            - '@translation.reader'
            - '@oro_translation.database_translation.persister'
            - '@doctrine'
            - '%kernel.cache_dir%'
            - '@logger'
        lazy: true
        tags:
            - { name: monolog.logger, channel: oro_translation }

    Oro\Bundle\TranslationBundle\Download\CachingTranslationMetricsProvider:
        arguments:
            - '@Oro\Bundle\TranslationBundle\Download\OroTranslationServiceAdapter'
            - '@oro_translation.cache'
            - '@logger'
        tags:
            - { name: monolog.logger, channel: oro_translation }

    Oro\Bundle\TranslationBundle\Download\OroTranslationServiceAdapter:
        arguments:
            - !service { class: GuzzleHttp\Client }
            - '@logger'
            - '%oro_translation.package_names%'
            - { apikey: '%oro_translation.translation_service.apikey%' }
        tags:
            - { name: monolog.logger, channel: oro_translation }

    oro_translation.database_translation.metadata.cache:
        class: Oro\Bundle\TranslationBundle\Translation\DynamicTranslationMetadataCache
        arguments:
            - '@oro_translation.database_translation.metadata.cache_impl'

    oro_translation.database_translation.metadata.cache_impl:
        public: false
        parent: oro.cache.abstract
        calls:
            - [ setNamespace, [ 'oro_db_trans_metadata' ] ]

    oro_translation.database_translation.persister:
        class: Oro\Bundle\TranslationBundle\Translation\DatabasePersister
        arguments:
            - '@doctrine'
            - '@oro_translation.manager.translation'

    oro_translation.database_translation.loader:
        class: Oro\Bundle\TranslationBundle\Translation\OrmTranslationLoader
        public: true
        arguments:
            - '@doctrine'
            - '@oro_translation.database_checker'
        tags:
            - { name: translation.loader, alias: oro_database_translation }

    oro_translation.database_checker:
        public: false
        class: Oro\Bundle\EntityBundle\Tools\DatabaseChecker
        arguments:
            - '@doctrine'
            - ['oro_translation']
            - '%installed%'
        tags:
            - { name: oro_entity.database_checker }

    oro_translation.empty_array.loader:
        class: Oro\Bundle\TranslationBundle\Translation\EmptyArrayLoader

    oro_translation.selector:
        class: Oro\Bundle\TranslationBundle\Translation\MessageSelector
        decorates: translator.selector
        arguments:
            - '@logger'

    oro_translation.cache:
        parent: oro.cache.abstract
        calls:
            - [setNamespace, [ 'oro_trans' ] ]

    oro_translation.resource.cache:
        public: false
        class: Doctrine\Common\Cache\ArrayCache

    oro_translation.cache.translation_cache_warmer:
        class: Oro\Bundle\TranslationBundle\Cache\TranslationCacheWarmer
        public: false
        decorates: 'translation.warmer'
        decoration_inner_name: 'translation.warmer.default'
        arguments:
            - '@translation.warmer.default'
            - '@oro_translation.strategy.provider'

    oro_translation.js_dumper:
        class: Oro\Bundle\TranslationBundle\Provider\JsTranslationDumper
        arguments:
            - '@oro_translation.controller'
            - '@router'
            - '%oro_translation.js_translation.domains%'
            - '%kernel.project_dir%'
            - '@oro_translation.provider.language'
        lazy: true
        public: true

    oro_translation.twig.translation.extension:
        class: Oro\Bundle\TranslationBundle\Twig\TranslationExtension
        public: false
        arguments:
            - '@oro_platform.twig.service_locator'
            - '%oro_translation.debug_translator%'
            - '%oro_translation.js_translation.debug%'
        tags:
            - { name: twig.extension }

    oro_translation.query_hint.translatable:
        public: false
        abstract: true
        tags:
            -
                name: oro_entity.query_hint
                hint: oro_translation.translatable
                alias: HINT_TRANSLATABLE
                output_walker: Oro\Component\DoctrineUtils\ORM\Walker\TranslatableSqlWalker

    oro_translation.event_listener.translation:
        class: Oro\Bundle\TranslationBundle\EventListener\TranslationListener
        lazy: true
        arguments:
            - '@oro_translation.database_translation.metadata.cache'
            - 'import.language_translations_import_from_csv'
        tags:
            - {name: kernel.event_listener, event: oro.import_export.after_job_execution, method: onAfterImportTranslations}

    oro_translation.strategy.default:
        class: Oro\Bundle\TranslationBundle\Strategy\DefaultTranslationStrategy
        public: false
        arguments:
            - '@oro_translation.provider.language'
            - '%installed%'
        tags:
            - { name: oro_translation.extension.translation_strategy }

    oro_translation.strategy.provider:
        class: Oro\Bundle\TranslationBundle\Strategy\TranslationStrategyProvider
        arguments:
            - !tagged_iterator oro_translation.extension.translation_strategy

    Oro\Bundle\TranslationBundle\EventListener\Datagrid\LanguageTranslationCompletenessAndAvailabilityListener:
        arguments:
            - '@Oro\Bundle\TranslationBundle\Download\CachingTranslationMetricsProvider'
            - '@doctrine'
        tags:
            - { name: kernel.event_listener, event: oro_datagrid.orm_datasource.result.after.oro-translation-language-grid }

    oro_translation.listener.datagrid.translation:
        class: Oro\Bundle\TranslationBundle\EventListener\Datagrid\TranslationListener
        arguments:
            - '@oro_translation.provider.language'
        tags:
            - { name: kernel.event_listener, event: oro_datagrid.datagrid.build.before.oro-translation-translations-grid, method: onBuildBefore }

    oro_translation.listener.datagrid.translatable:
        class: Oro\Bundle\TranslationBundle\EventListener\Datagrid\TranslatableListener
        tags:
            - { name: kernel.event_listener, event: oro_datagrid.orm_datasource.result.before, method: onResultBefore }

    oro_translation.repository.language:
        class: Oro\Bundle\TranslationBundle\Entity\Repository\LanguageRepository
        parent: oro_entity.abstract_repository
        arguments:
            - 'Oro\Bundle\TranslationBundle\Entity\Language'

    oro_translation.provider.translation_context:
        class: Oro\Bundle\TranslationBundle\Provider\TranslationContextProvider
        public: true
        arguments:
            - !tagged_iterator oro_translation.extension.translation_context_resolver

    oro_translation.extension.translation_context_resolver:
        class: Oro\Bundle\TranslationBundle\Extension\TranslationContextResolver
        arguments:
            - '@translator'
        tags:
            - { name: oro_translation.extension.translation_context_resolver, priority: -100 }

    oro_translation.provider.language:
        class: Oro\Bundle\TranslationBundle\Provider\LanguageProvider
        arguments:
            - '@doctrine'
            - '@oro_locale.settings'
            - '@oro_security.acl_helper'

    oro_translation.manager.translation:
        class: Oro\Bundle\TranslationBundle\Manager\TranslationManager
        public: true
        arguments:
            - '@doctrine'
            - '@oro_translation.provider.translation_domain'
            - '@oro_translation.database_translation.metadata.cache'
            - '@event_dispatcher'

    oro_translation.cache.provider.domains:
        parent: oro.cache.abstract
        public: false
        calls:
            - [ setNamespace, [ 'oro_translation_domains' ] ]

    oro_translation.provider.translation_domain:
        class: Oro\Bundle\TranslationBundle\Provider\TranslationDomainProvider
        public: true
        arguments:
            - '@doctrine'
            - '@oro_translation.cache.provider.domains'

    oro_translation.helper.translation:
        class: Oro\Bundle\TranslationBundle\Helper\TranslationHelper
        arguments:
            - '@doctrine'

    oro_translation.filter.language:
        class: Oro\Bundle\TranslationBundle\Filter\LanguageFilter
        public: false
        arguments:
            - '@form.factory'
            - '@oro_filter.filter_utility'
            - '@doctrine'
        tags:
            - { name: oro_filter.extension.orm_filter.filter, type: language }

    oro_translation.helper.translation_route:
        class: Oro\Bundle\TranslationBundle\Helper\TranslationsDatagridRouteHelper
        arguments:
            - '@oro_datagrid.helper.route'

    oro_translation.layout.data_provider.translator:
        class: Oro\Bundle\TranslationBundle\Layout\DataProvider\TranslatorProvider
        arguments:
            - '@translator'
        tags:
            - { name: layout.data_provider, alias: translator }

    oro_translation.rebuild_translation_cache_processor:
        class: Oro\Bundle\TranslationBundle\Cache\RebuildTranslationCacheProcessor
        arguments:
            - '@translator.default'
            - '@oro_translation.provider.translation_domain'
            - '@oro_translation.js_dumper'
            - '@oro_ui.dynamic_asset_version_manager'
            - '@logger'

    oro_translation.rebuild_translation_cache_handler:
        class: Oro\Bundle\TranslationBundle\Cache\RebuildTranslationCacheHandler
        arguments:
            - '@oro_translation.rebuild_translation_cache_processor'

    oro_translation.rebuild_translation_cache_action:
        class: Oro\Bundle\TranslationBundle\Action\RebuildTranslationCacheAction
        arguments:
            - '@oro_action.expression.context_accessor'
            - '@oro_translation.rebuild_translation_cache_handler'
            - '@translator.default'
        tags:
            - { name: oro_action.action, alias: rebuild_translation_cache }

    Oro\Bundle\TranslationBundle\Action\DownloadUpdateLanguageTranslationAction:
        arguments:
            - '@oro_action.expression.context_accessor'
            - '@Oro\Bundle\TranslationBundle\Download\TranslationDownloader'
        tags:
            - { name: oro_action.action, alias: download_update_language_translation }

    Oro\Bundle\TranslationBundle\Action\GetLanguageTranslationMetricsAction:
        arguments:
            - '@oro_action.expression.context_accessor'
            - '@Oro\Bundle\TranslationBundle\Download\CachingTranslationMetricsProvider'
        tags:
            - { name: oro_action.action, alias: get_language_translation_metrics }

    Oro\Bundle\TranslationBundle\Action\IsLanguageTranslationInstallAvailableCondition:
        arguments:
            - '@Oro\Bundle\TranslationBundle\Download\CachingTranslationMetricsProvider'
            - '@doctrine'
        tags:
            - { name: oro_action.condition, alias: is_language_translation_install_available }

    Oro\Bundle\TranslationBundle\Action\IsLanguageTranslationUpdateAvailableCondition:
        arguments:
            - '@Oro\Bundle\TranslationBundle\Download\CachingTranslationMetricsProvider'
            - '@doctrine'
        tags:
            - { name: oro_action.condition, alias: is_language_translation_update_available }

    oro_translation.mass_action.reset_translation:
        class: Oro\Bundle\TranslationBundle\Datagrid\Extension\MassAction\ResetTranslationsMassAction
        shared: false
        tags:
            - { name: oro_datagrid.extension.mass_action.type, type: reset_translations }

    oro_translation.mass_action.reset_translation_handler:
        class: Oro\Bundle\TranslationBundle\Datagrid\Extension\MassAction\ResetTranslationsMassActionHandler
        public: true
        arguments:
           - '@oro_translation.manager.translation'
           - '@translator'
           - '@oro_security.acl_helper'

    oro_translation.migration.demo_data_fixtures_listener.js_translation_dump:
        class: Oro\Bundle\TranslationBundle\EventListener\JsTranslationDumpDemoDataListener
        arguments:
            - '@oro_translation.js_dumper'
            - '@oro_translation.provider.language'
            - '%installed%'
        tags:
            - { name: kernel.event_listener, event: oro_migration.data_fixtures.post_load, method: onPostLoad, priority: -100 }

    oro_translation.async.dump_js_translations_processor:
        class: Oro\Bundle\TranslationBundle\Async\DumpJsTranslationsMessageProcessor
        arguments:
            - '@oro_translation.js_dumper'
            - '@logger'
        tags:
            - { name: 'oro_message_queue.client.message_processor' }
