services:
  oro_behat_extension.isolation.test_isolation_subscriber:
    class: 'Oro\Bundle\TestFrameworkBundle\Behat\Isolation\EventListener\TestIsolationSubscriber'
    arguments:
      - ~
    tags:
      - { name: 'event_dispatcher.subscriber', priority: 100 }

  oro_behat_extension.isolation.message_queue_isolation_subscriber:
    class: 'Oro\Bundle\TestFrameworkBundle\Behat\Isolation\EventListener\MessageQueueIsolationSubscriber'
    arguments:
      - '@symfony2_extension.kernel'
      - '@oro_test.processor.message_queue.dbal'
      - '@oro_test.processor.message_queue.amqp'
    tags:
      - { name: 'event_dispatcher.subscriber', priority: 150 }

  oro_behat_extension.isolation.unix_file_cache_isolator:
    class: 'Oro\Bundle\TestFrameworkBundle\Behat\Isolation\UnixFileCacheIsolator'
    arguments:
      - '@symfony2_extension.kernel'
      -
        - 'doctrine'
        - 'oro_data'
        - 'oro_entities'
        - 'translations'
      -
        - 'validation.php'
    tags:
      - { name: 'oro_behat.isolator', priority: 100 }

  oro_behat_extension.isolation.windows_file_cache_isolator:
    class: 'Oro\Bundle\TestFrameworkBundle\Behat\Isolation\WindowsFileCacheIsolator'
    arguments:
      - '@symfony2_extension.kernel'
      -
        - 'doctrine'
        - 'oro_data'
        - 'oro_entities'
        - 'translations'
      -
        - 'validation.php'
    tags:
      - { name: 'oro_behat.isolator', priority: 100 }

  oro_behat_extension.isolation.windows_mysql_isolator:
    class: 'Oro\Bundle\TestFrameworkBundle\Behat\Isolation\WindowsMysqlIsolator'
    arguments:
      - '@symfony2_extension.kernel'
    tags:
      - { name: 'oro_behat.isolator', priority: 110 }

  oro_behat_extension.isolation.unix_mysql_simple_isolator:
    class: 'Oro\Bundle\TestFrameworkBundle\Behat\Isolation\UnixMysqlIsolator'
    arguments:
      - '@symfony2_extension.kernel'
    tags:
      - { name: 'oro_behat.isolator', priority: 110 }

  oro_behat_extension.isolation.unix_pgsql_isolator:
    class: 'Oro\Bundle\TestFrameworkBundle\Behat\Isolation\UnixPgsqlIsolator'
    arguments:
      - '@symfony2_extension.kernel'
    tags:
      - { name: 'oro_behat.isolator', priority: 110 }

  oro_behat_extension.isolation.docker_pgsql_isolator:
    class: Oro\Bundle\TestFrameworkBundle\Behat\Isolation\DockerPgsqlIsolator
    arguments:
      - '@symfony2_extension.kernel'
    tags:
      - { name: 'oro_behat.isolator', priority: 110 }

  oro_behat_extension.isolation.docker_compose_pgsql_isolator:
    class: Oro\Bundle\TestFrameworkBundle\Behat\Isolation\DockerComposePgsqlIsolator
    arguments:
      - '@symfony2_extension.kernel'
    tags:
      - { name: 'oro_behat.isolator', priority: 110 }

  oro_behat_extension.isolation.docker_mysql_isolator:
    class: Oro\Bundle\TestFrameworkBundle\Behat\Isolation\DockerMysqlIsolator
    arguments:
      - '@symfony2_extension.kernel'
    tags:
      - { name: 'oro_behat.isolator', priority: 110 }

  oro_behat_extension.isolation.docker_compose_mysql_isolator:
    class: Oro\Bundle\TestFrameworkBundle\Behat\Isolation\DockerComposeMysqlIsolator
    arguments:
      - '@symfony2_extension.kernel'
    tags:
      - { name: 'oro_behat.isolator', priority: 110 }

  oro_behat_extension.isolation.kernel_isolator:
    class: 'Oro\Bundle\TestFrameworkBundle\Behat\Isolation\KernelIsolator'
    arguments:
      - '@symfony2_extension.kernel'
    tags:
      - { name: 'oro_behat.isolator', priority: 120 }

  oro_behat_extension.isolation.inital_massage_queue_isolator:
    class: 'Oro\Bundle\TestFrameworkBundle\Behat\Isolation\InitalMessageQueueIsolator'
    arguments:
      - '@symfony2_extension.kernel'
      - '@oro_test.processor.message_queue.dbal'
      - '@oro_test.processor.message_queue.amqp'
    tags:
      - { name: 'oro_behat.isolator', priority: 50 }

  oro_behat_extension.isolation.doctrine_isolator:
    class: 'Oro\Bundle\TestFrameworkBundle\Behat\Isolation\DoctrineIsolator'
    arguments:
      - '@symfony2_extension.kernel'
      - '@oro_test.context.fixture_loader'
      - '@oro_test.alice_loader'
    tags:
      - { name: 'oro_behat.isolator', priority: 300 }

  oro_behat_extension.isolation.import_export:
    class: 'Oro\Bundle\TestFrameworkBundle\Behat\Isolation\ImportExportIsolator'
    arguments:
      - '@symfony2_extension.kernel'
    tags:
      - { name: 'oro_behat.isolator', priority: 200 }
