services:
    oro_help.configuration.provider:
        class: Oro\Bundle\HelpBundle\Configuration\ConfigurationProvider
        public: false
        parent: oro.static_config_provider.abstract
        arguments:
            - '%kernel.cache_dir%/oro/help.php'
            - '%kernel.debug%'

    oro_help.help_link.cache:
        parent: oro.cache.abstract
        calls:
            - [ setNamespace, [ 'oro_help_link' ] ]

    oro_help.help_link_provider:
        class: Oro\Bundle\HelpBundle\Provider\HelpLinkProvider
        arguments:
            - [] # default configuration. Set by Oro\Bundle\HelpBundle\DependencyInjection\OroHelpExtension
            - '@oro_help.configuration.provider'
            - '@request_stack'
            - '@oro_ui.controller_class_provider'
            - '@controller_name_converter'
            - '@oro_platform.composer.version_helper'
            - '@oro_help.help_link.cache'

    oro_help.twig.extension:
        class: Oro\Bundle\HelpBundle\Twig\HelpExtension
        public: false
        arguments:
            - '@oro_platform.twig.service_locator'
        tags:
            - { name: twig.extension }
