bundles:
    - Gos\Bundle\WebSocketBundle\GosWebSocketBundle
    - { name: Gos\Bundle\PubSubRouterBundle\GosPubSubRouterBundle, priority: -250 }
    - { name: Oro\Bundle\SyncBundle\OroSyncBundle, priority: -246 }
