oro_sync.ping:
    channel: 'oro/ping'
    handler:
        callback: 'oro_sync.ping'

oro_sync.data_update:
    channel: 'oro/data/update'
    handler:
        callback: 'oro_sync.data_update'

oro_sync.maintenance:
    channel: 'oro/maintenance'
    handler:
        callback: 'oro_sync.maintenance'
