app-modules:
    - oroviewswitcher/js/app/modules/device-emulate-module
configs:
    oroviewswitcher/js/app/modules/device-emulate-module: {}
    oroviewswitcher/js/app/views/device-switcher-view: {}
dynamic-imports:
    oroviewswitcher:
        - oroviewswitcher/js/app/views/device-switcher-view
        - oroviewswitcher/js/app/services/inner-page-model-service
