css:
    inputs:
        # Settings
        - 'bundles/oroui/css/scss/settings/global-settings.scss'

        # Styles
        - '~timepicker/jquery.timepicker.css'

        - '~jstree/dist/themes/default/style.min.css'

        # Bootstrap port
        - 'bundles/oroui/css/scss/bootstrap/bootstrap.scss'

        # Libraries styles
        - 'bundles/oroui/css/scss/font-awesome/core.scss'
        - 'bundles/oroui/lib/simplecolorpicker/jquery.simplecolorpicker.css'
        - 'bundles/oroui/lib/simplecolorpicker/jquery.simplecolorpicker-fontawesome.css'
        - 'bundles/oroui/lib/minicolors/jquery.minicolors.css'
        - '~lightgallery/dist/css/lg-transitions.css'
        - '~lightgallery/dist/css/lightgallery.css'
        - '~overlayscrollbars/css/OverlayScrollbars.css'
        - '~jquery-ui-multiselect-widget/jquery.multiselect.css'
        - '~jquery-ui-multiselect-widget/jquery.multiselect.filter.css'

        # customized libraries' styles
        - 'bundles/oroui/css/jquery-ui.grid.css'
        - 'bundles/oroui/css/jquery-ui.custom.css'
        - 'bundles/oroui/css/lightgallery/lightgallery.scss'

        # custom styles
        - 'bundles/oroui/css/scss/main.scss'
        - 'bundles/oroui/css/all.css'
    output: css/oro.css
    auto_rtl_inputs:
        - 'bundles/oro*/**'
