services:
    oro_theme.registry:
        class: Oro\Bundle\ThemeBundle\Model\ThemeRegistry
        arguments:
            - '%oro_theme.settings%'

    Oro\Bundle\ThemeBundle\Model\ThemeRegistry:
        alias: oro_theme.registry

    oro_theme.twig.extension:
        class: Oro\Bundle\ThemeBundle\Twig\ThemeExtension
        public: false
        arguments:
            - '@oro_platform.twig.service_locator'
        tags:
            - { name: twig.extension }
