oro_translation_jstranslation:
    path:      /media/js/translation/{_locale}.json
    defaults:  { _controller:  oro_translation.controller:indexAction }
    options:
        expose: true

oro_translation_service:
    resource:     "@OroTranslationBundle/Controller"
    type:         annotation
    prefix:       /translation

oro_translation_language:
    resource:     "@OroTranslationBundle/Controller/LanguageController.php"
    type:         annotation
    prefix:       /language

oro_translation_bundle_api:
    resource:     "@OroTranslationBundle/Resources/config/oro/routing_api.yml"
    type:         rest
    prefix:       api/rest/{version}
    requirements:
        version:  latest|v1
        _format:  json
    defaults:
        version:  latest
