styles:
    inputs:
        - 'bundles/orodatagrid/blank/scss/variables/no-data-config.scss'
        - 'bundles/orodatagrid/blank/scss/variables/datagrid-table-config.scss'
        - 'bundles/orodatagrid/blank/scss/variables/datagrid-header-cell-config.scss'
        - 'bundles/orodatagrid/blank/scss/variables/datagrid-body-cell-config.scss'
        - 'bundles/orodatagrid/blank/scss/variables/more-bar-holder-config.scss'

        - 'bundles/orodatagrid/blank/scss/styles.scss'
