placeholders:
    placeholders:
        change_history_block:
            items:
                change_history_link: ~
        segment_criteria_list:
            items:
                data_audit_condition: ~

    items:
        change_history_link:
            template: OroDataAuditBundle::change_history_link.html.twig
            applicable:
                - "@oro_dataaudit.placeholder.filter->isEntityAuditable($entity$, $audit_show_change_history$)"
                - "@oro_user.placeholder.filter->isUserApplicable()"
            acl: oro_dataaudit_view
        data_audit_condition:
            acl: oro_dataaudit_view
            applicable:
                - "@oro_dataaudit.segment_widget.context_checker->isApplicableInContext($params$)"
            template: OroDataAuditBundle:Segment:data_audit_condition.html.twig
