doctrine:
    orm:
        entity_managers:
            config:
                mappings:
                    OroConfigBundle:
                        mapping:   true
                        is_bundle: true

oro_message_queue:
    persistent_services:
        - 'oro_config.cache'
