services:
    _defaults:
        public: true

    Oro\Bundle\AttachmentBundle\Controller\FileController:
        calls:
            - ['setContainer', ['@Psr\Container\ContainerInterface']]
        tags:
            - { name: container.service_subscriber }
            - { name: container.service_subscriber, id: oro_attachment.file_manager }
            - { name: container.service_subscriber, id: oro_attachment.manager.image_resize }
            - { name: container.service_subscriber, id: oro_attachment.provider.file_name }
