# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    BeyondCapable\Core\:
        resource: '../../../../../src/Core'
        exclude:
            - '../../../../../src/Core/Platform/DependencyInjection/'
            - '../../../../../src/Core/Platform/Domain/Entity/'
            - '../../../../../src/Kernel.php'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    BeyondCapable\Core\Platform\Persistence\Doctrine\Repository\:
        resource: '../../../../../src/Core/Platform/Persistence/Doctrine/Repository'

    beyond_capable.core.platform.presenter.controller.site.default:
        class: BeyondCapable\Core\Platform\Presenter\Controller\Site\DefaultController
        public: true

    beyond_capable.core.platform.presenter.controller.site.portfolio:
        class: BeyondCapable\Core\Platform\Presenter\Controller\Site\PortfolioController
        public: true

    beyond_capable.core.platform.presenter.controller.dashboard:
        class: BeyondCapable\Core\Platform\Presenter\Controller\DashboardController
        public: true