services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    BeyondCapable\Core\Platform\TestWork\Acceptence\:
        resource: '../../TestWork/Acceptence/*'
