services:
    oro_entity.tests.event_listener.doctrine_flush_progress_listener:
        alias: oro_entity.event_listener.doctrine_flush_progress_listener
        public: true

    oro_entity.tests.event_listener.user_preloading:
        parent: oro_entity.event_listener.default_preloading
        public: true
