entity_config:
    ownership:
        entity:
            items:
                owner_type:
                    options:
                        create_only:        true
                        priority:           100
                        indexed:            true
                    grid:
                        type:               select
                        label:              'Ownership Type'
                        filter_type:        choice
                        required:           true
                        sortable:           true
                        filterable:         true
                        show_filter:        true
                        choices:            "@oro_organization.form.type.ownership_type->getOwnershipsArray"
                    form:
                        type:               Oro\Bundle\OrganizationBundle\Form\Type\OwnershipType
                        options:
                            block:          other
                            required:       true
                            label:          'Ownership Type'

