entity_config:
    importexport:
        field:
            form:
                block_config:
                    import_export:
                        title:              oro.importexport.entity_config.block_title
                        priority:           30
            items:
                # custom field header, by default field label is used
                header:
                    options:
                        value_type:         string
                    form:
                        type:               Symfony\Component\Form\Extension\Core\Type\TextType
                        options:
                            label:          oro.importexport.entity_config.header.label
                            required:       false
                            block:          import_export
                            tooltip:        oro.importexport.entity_config.header.tooltip
                # field order in result file
                order:
                    options:
                        value_type:         integer
                    form:
                        type:               Symfony\Component\Form\Extension\Core\Type\IntegerType
                        options:
                            label:          oro.importexport.entity_config.order.label
                            scale:          0
                            empty_data:     ''
                            required:       false
                            block:          import_export
                # is field will be used to find existing entity
                identity:
                    options:
                        value_type:         integer
                        allowed_type:       [string, text, integer, smallint, bigint, boolean, date, float, decimal, money, percent, enum, ref-one, manyToOne]
                        immutable_type:     [ref-one, manyToOne]
                    form:
                        type:               Oro\Bundle\ImportExportBundle\Form\Type\IdentityConfigChoiceType
                        options:
                            label:          oro.importexport.entity_config.identity.label
                            placeholder:    false
                            required:       false
                            block:          import_export
                            tooltip:        oro.importexport.entity_config.identity.tooltip
                # is field must be excluded from import/export
                excluded:
                    options:
                        value_type:         boolean
                    form:
                        type:               Symfony\Component\Form\Extension\Core\Type\ChoiceType
                        options:
                            label:          oro.importexport.entity_config.excluded.label
                            choices:
                                No:         0
                                Yes:        1
                            placeholder:    false
                            required:       false
                            block:          import_export
                # is relation must be represented by all it's fields
                full:
                    options:
                        allowed_type:       [ref-one, ref-many, manyToOne, oneToMany, manyToMany]
                    form:
                        type:               Symfony\Component\Form\Extension\Core\Type\ChoiceType
                        options:
                            label:          oro.importexport.entity_config.full.label
                            choices:
                                Identity only: 0
                                All:        1
                            placeholder:    false
                            required:       false
                            block:          import_export
                            tooltip:        'oro.importexport.entity_config.full.tooltip'

                # is relation field should be processed as scalar value when exporting data
                process_as_scalar:
                    options:
                        allowed_type:       [ref-one, ref-many, manyToOne, oneToMany, manyToMany]
                        default_value:      false
