placeholders:
    placeholders:
        import_validate_export_messages:
            items:
                import_additional_notices: ~
    items:
        import_additional_notices:
            template: OroImportExportBundle:ImportExport:additionalNotices.html.twig
