services:
    oro_dataaudit.tests.migration_listener:
        class: Oro\Bundle\DataAuditBundle\Tests\Functional\Environment\TestEntitiesMigrationListener
        tags:
            - { name: kernel.event_listener, event: oro_migration.post_up, method: onPostUp }

    oro_dataaudit.tests.entity_class_name_provider:
        class: Oro\Bundle\DataAuditBundle\Tests\Functional\Environment\StubEntityClassNameProvider
        tags:
            - { name: oro_entity.class_name_provider, priority: 255 }
