entity_config:
    email:
        field:
            items:
                available_in_template:
                    options:
                        value_type:         boolean
                        default_value:      true
                        allowed_type:       [string, text, integer, smallint, bigint, boolean, datetime, date, time, float, decimal, money, percent, enum, multiEnum, file, image, ref-one, manyToOne, simple_array, guid]
                    form:
                        type:               Symfony\Component\Form\Extension\Core\Type\ChoiceType
                        options:
                            choices:
                                No:         0
                                Yes:        1
                            placeholder:    false
                            block:          other
                            label:          oro.email.entity_config.email.field.items.available_in_template
    attachment:
        entity:
            items:
                auto_link_attachments:
                    options:
                        require_schema_update:  false
                        priority:               100
                        default_value:          false
                    form:
                        type:                   Oro\Bundle\EmailBundle\Form\Type\EmailLinkToScopeType
                        options:
                            block:              attachments
                            choices:
                                oro.email.system_configuration.attachment_configuration.link_to_scope.choices.manual.label: 0
                                oro.email.system_configuration.attachment_configuration.link_to_scope.choices.auto.label: 1
                            placeholder:        false
                            required:           true
                            label:              oro.email.system_configuration.attachment_configuration.link_to_scope.label
