workflows:
    oro_test_workflow:
        entity: Oro\Bundle\TestFrameworkBundle\Entity\Item

        defaults: {active: true}

        start_step: first
        steps:
            first:
                order: 10
                allowed_transitions:
                    - to_second_transition
            second:
                order: 20

        transitions:
            __start__:
                is_start: true
                is_hidden: true
                step_to: first
                transition_definition: __start___definition
            to_second_transition:
                step_to: second
                transition_definition: to_second_transition_definition

        transition_definitions:
            __start___definition: ~
            to_second_transition_definition: ~
