services:
    _defaults:
        public: true

    Oro\Bundle\ActivityListBundle\Controller\ActivityListController:
        calls:
            - ['setContainer', ['@Psr\Container\ContainerInterface']]
        tags:
            - { name: container.service_subscriber }
            - { name: container.service_subscriber, id: 'oro_config.user' }
            - { name: container.service_subscriber, id: 'oro_filter.extension.orm_filter_bag' }
            - { name: container.service_subscriber, id: 'oro_activity_list.provider.chain' }
