services:
    _defaults:
        public: false

    Oro\Bundle\LoggerBundle\Command\LoggerEmailNotificationCommand:
        arguments:
            - '@validator'
            - '@?oro_config.global'
        tags:
            - { name: console.command }

    Oro\Bundle\LoggerBundle\Command\LoggerLevelCommand:
        arguments:
            - '@?oro_config.global'
            - '@?oro_config.user'
            - '@oro_logger.cache'
            - '@?oro_user.manager'
        tags:
            - { name: console.command }
