parameters:
    oro_logger.detailed_logs_default_level: error
services:
    oro_logger.cache:
        class: Doctrine\Common\Cache\ArrayCache
        public: true
        lazy: true
        calls:
            - [ setNamespace, [ 'oro_logger' ] ]

    oro_logger.event_subscriber.console_command:
        class: Oro\Bundle\LoggerBundle\EventSubscriber\ConsoleCommandSubscriber
        arguments:
            - '@logger'
        tags:
            - { name: kernel.event_subscriber }
            - { name: monolog.logger, channel: console }

    oro_logger.monolog.db_logs.handler:
        class: Oro\Bundle\LoggerBundle\Monolog\DBLogsHandler
        calls:
            - ['setContainer', ['@service_container']]
            - ['setFormatter', ['@monolog.formatter.normalizer']]

    oro_logger.log_level_config_provider:
        class: Oro\Bundle\LoggerBundle\Monolog\LogLevelConfig
        arguments:
            - '@oro_logger.cache'
            - '@?oro_config.user'
            - '%installed%'
            - '%oro_logger.detailed_logs_default_level%'

    oro_logger.message_factory:
        class: Oro\Bundle\LoggerBundle\Mailer\MessageFactory
        calls:
            - ['setContainer', ['@service_container']]

    swiftmailer.plugin.no_recipient.abstract:
        class: Oro\Bundle\LoggerBundle\Mailer\NoRecipientPlugin
        abstract: true

    oro_logger.processor.log_message:
        class: Monolog\Processor\PsrLogMessageProcessor
        tags:
            - { name: monolog.processor }

    oro_logger.consumption_extension.interruption_detail:
        class: Oro\Bundle\LoggerBundle\Async\Extension\InterruptionDetailConsumptionExtension
        public: false
        arguments:
            - '@service_container'
            - '@oro_message_queue.log.message_processor_class_provider'
        tags:
            - { name: oro_message_queue.consumption.extension, persistent: true }

    oro_logger.validator.email_recipients_list:
        class: Oro\Bundle\LoggerBundle\Validator\EmailRecipientsListValidator
        tags:
            - { name: validator.constraint_validator, alias: oro_logger.validator.email_recipients_list }

    oro_logger.deduplication_handler.cache.warmer:
        public: false
        class: Oro\Bundle\LoggerBundle\Cache\DeduplicationHandlerCacheWarmer
        arguments:
            - '@?monolog.handler.deduplicated'
        tags:
            - { name: kernel.cache_warmer, priority: -1000 }
