entity_config:
    workflow:
        entity:
            items:
                show_step_in_grid:
                    options:
                        priority:           250
                        default_value:      true
                    form:
                        type:               Symfony\Component\Form\Extension\Core\Type\ChoiceType
                        options:
                            label:          oro.workflow.entity_config.show_step_in_grid.label
                            required:       false
                            choices:
                                oro.workflow.entity_config.show_step_in_grid.choice.hide: 0
                                oro.workflow.entity_config.show_step_in_grid.choice.show: 1
                            placeholder:    false
                            block:          other
