services:
    oro_workflow.twig.extension.workflow:
        class: 'Oro\Bundle\WorkflowBundle\Twig\WorkflowExtension'
        public: false
        arguments:
            - '@oro_platform.twig.service_locator'
        tags:
            - { name: twig.extension }
