services:
    _defaults:
        public: false

    Oro\Bundle\ReminderBundle\Command\SendRemindersCommand:
        arguments:
            - '@doctrine'
            - '@oro_reminder.sender'
        tags:
            - { name: console.command }
