system_configuration:
    groups:
        email_notifications_settings:
            title: oro.notification.system_configuration.title
        email_mass_notifications_settings:
            title: oro.notification.system_configuration.mass_notification.title

    fields:
        oro_notification.email_notification_sender_email:
            data_type: string
            type: Symfony\Component\Form\Extension\Core\Type\EmailType
            search_type: text
            options:
                label: oro.notification.system_configuration.email_notification_sender_email
                required: true
                constraints:
                    - NotBlank: ~
                    - Email: ~
        oro_notification.email_notification_sender_name:
            data_type: string
            type: Symfony\Component\Form\Extension\Core\Type\TextType
            search_type: text
            options:
                label: oro.notification.system_configuration.email_notification_sender_name
                required: true
                constraints:
                    - NotBlank: ~
        oro_notification.mass_notification_template:
            data_type: string
            type: Oro\Bundle\EmailBundle\Form\Type\SystemEmailTemplateSelectType
            priority: 20
            options:
                required: false
                label: oro.notification.system_configuration.mass_notification.template
                tooltip: oro.notification.system_configuration.mass_notification.template.tooltip
        oro_notification.mass_notification_recipients:
            data_type: string
            type: Symfony\Component\Form\Extension\Core\Type\TextareaType
            search_type: text
            priority: 10
            options:
                required: false
                label: oro.notification.system_configuration.mass_notification.recipients
                tooltip: oro.notification.system_configuration.mass_notification.recipients.tooltip
    tree:
        system_configuration:
            platform:
                children:
                    general_setup:
                        children:
                            email_configuration:
                                children:
                                    email_notifications_settings:
                                        priority: 20
                                        children:
                                            - oro_notification.email_notification_sender_email
                                            - oro_notification.email_notification_sender_name
                                    email_mass_notifications_settings:
                                        priority: 10
                                        children:
                                            - oro_notification.mass_notification_recipients
                                            - oro_notification.mass_notification_template
    api_tree:
        email_configuration:
            oro_notification.email_notification_sender_email: ~
            oro_notification.email_notification_sender_name: ~
