system_configuration:
    groups:
        user_settings:
            icon:  fa-key
            title: oro.user.system_configuration.groups.user_settings.title
        password_complexity_rules:
            icon:  fa-usd
            title: oro.user.system_configuration.groups.password_complexity_rules.title
        email_settings:
            title: oro.user.system_configuration.groups.email_settings.title
    fields:
        oro_user.password_min_length:
            data_type: integer
            type: Symfony\Component\Form\Extension\Core\Type\IntegerType
            search_type: text
            priority: 40
            options:
                label:  oro.user.system_configuration.fields.password_min_length.label
                required: true
                constraints:
                    - NotBlank: ~
                    - Range:
                        min: 1
                    - Type:
                        type: integer

        oro_user.password_numbers:
            data_type: boolean
            type: Oro\Bundle\ConfigBundle\Form\Type\ConfigCheckbox
            priority: 30
            options:
                label: oro.user.system_configuration.fields.password_numbers.label
                required: false

        oro_user.password_lower_case:
            data_type: boolean
            type: Oro\Bundle\ConfigBundle\Form\Type\ConfigCheckbox
            priority: 25
            options:
                label: oro.user.system_configuration.fields.password_lower_case.label
                required: false

        oro_user.password_upper_case:
            data_type: boolean
            type: Oro\Bundle\ConfigBundle\Form\Type\ConfigCheckbox
            priority: 20
            options:
                label: oro.user.system_configuration.fields.password_upper_case.label
                required: false

        oro_user.password_special_chars:
            data_type: boolean
            type: Oro\Bundle\ConfigBundle\Form\Type\ConfigCheckbox
            priority: 10
            options:
                label: oro.user.system_configuration.fields.password_special_chars.label
                tooltip: oro.user.system_configuration.fields.password_special_chars.tooltip
                required: false

        oro_user.send_password_in_invitation_email:
            data_type: boolean
            type: Oro\Bundle\ConfigBundle\Form\Type\ConfigCheckbox
            priority: 10
            options:
                label: oro.user.system_configuration.fields.send_password_in_invitation_email.label
                tooltip: oro.user.system_configuration.fields.send_password_in_invitation_email.tooltip
                required: false

        oro_user.case_insensitive_email_addresses_enabled:
            data_type: boolean
            type: Oro\Bundle\ConfigBundle\Form\Type\ConfigCheckbox
            options:
                label: oro.user.system_configuration.fields.case_insensitive_email_addresses_enabled.label
                tooltip: oro.user.system_configuration.fields.case_insensitive_email_addresses_enabled.tooltip
                required: false
                resettable: false
                constraints:
                    - Oro\Bundle\UserBundle\Validator\Constraints\EmailCaseInsensitiveOptionConstraint: ~

    tree:
        system_configuration:
            platform:
                children:
                    general_setup:
                        children:
                            user_settings:
                                priority: 100
                                children:
                                    password_complexity_rules:
                                        children:
                                            - oro_user.password_min_length
                                            - oro_user.password_numbers
                                            - oro_user.password_lower_case
                                            - oro_user.password_upper_case
                                            - oro_user.password_special_chars
                                            # The backend user should not be able to enable this option in the UI
                                            #- oro_user.send_password_in_invitation_email
                                    email_settings:
                                        children:
                                            - oro_user.case_insensitive_email_addresses_enabled
