services:
    Oro\Bundle\CacheBundle\Command\InvalidateCacheScheduleCommand:
        public: false
        class: Oro\Bundle\CacheBundle\Command\InvalidateCacheScheduleCommand
        tags:
            - { name: console.command }
