system_configuration:
    groups:
        activity_list_settings:
            title:  oro.activitylist.system_configuration.activity_list.label

    fields:
        oro_activity_list.sorting_field:
            data_type: string
            type: Symfony\Component\Form\Extension\Core\Type\ChoiceType
            search_type: choice
            options:
                label: oro.activitylist.system_configuration.fields.sorting_field.label
                choices:
                    oro.activitylist.system_configuration.fields.sorting_field.choices.createdAt: createdAt
                    oro.activitylist.system_configuration.fields.sorting_field.choices.updatedAt: updatedAt
                required: true
                constraints:
                    - NotBlank: ~
        oro_activity_list.sorting_direction:
            data_type: string
            type: Symfony\Component\Form\Extension\Core\Type\ChoiceType
            search_type: choice
            options:
                label: oro.activitylist.system_configuration.fields.sorting_direction.label
                choices:
                    oro.activitylist.system_configuration.fields.sorting_direction.choices.DESC: DESC
                    oro.activitylist.system_configuration.fields.sorting_direction.choices.ASC: ASC
                required: true
                constraints:
                    - NotBlank: ~
        oro_activity_list.per_page:
            data_type: integer
            type: Symfony\Component\Form\Extension\Core\Type\ChoiceType
            search_type: choice
            options:
                label: oro.activitylist.system_configuration.fields.per_page.label
                choices:
                    10:     10
                    25:     25
                    50:     50
                    100:    100
                required: true
                constraints:
                    - NotBlank: ~
        oro_activity_list.grouping:
            data_type: boolean
            type: Symfony\Component\Form\Extension\Core\Type\ChoiceType
            search_type: choice
            options:
                label: oro.activitylist.system_configuration.email_threads.use_threads_in_activities.label
                choices:
                    oro.activitylist.system_configuration.email_threads.use_threads_in_activities.choices.non_threaded.label: 0
                    oro.activitylist.system_configuration.email_threads.use_threads_in_activities.choices.threaded.label: 1

    tree:
        system_configuration:
            platform:
                children:
                    general_setup:
                        children:
                            look_and_feel:
                                children:
                                    activity_list_settings:
                                        children:
                                            - oro_activity_list.sorting_field
                                            - oro_activity_list.sorting_direction
                                            - oro_activity_list.per_page
                            email_configuration:
                                children:
                                    email_threads:
                                        children:
                                            - oro_activity_list.grouping
        user_configuration:
            platform:
                children:
                    general_setup:
                        children:
                            look_and_feel:
                                children:
                                    activity_list_settings:
                                        children:
                                            - oro_activity_list.sorting_field
                                            - oro_activity_list.sorting_direction
                                            - oro_activity_list.per_page
                            user_email_configuration:
                                children:
                                    email_threads:
                                        children:
                                            - oro_activity_list.grouping

    api_tree:
        activity_list:
            oro_activity_list.sorting_field: ~
            oro_activity_list.sorting_direction: ~
            oro_activity_list.per_page: ~
        email_threads:
            oro_activity_list.grouping: ~
