services:
    oro_locale.cache:
        parent: oro.cache.abstract
        calls:
            - [ setNamespace, [ 'oro_locale' ] ]

    oro_locale.cache.provider.tree_fallback_strategy:
        parent: oro.cache.abstract
        public: false
        calls:
            - [ setNamespace, [ 'oro_locale_tree_fallback_strategy' ] ]

    oro_locale.localization.localization_provider.cache.warmer:
        class: Oro\Component\Config\Cache\ConfigCacheWarmer
        public: false
        arguments:
            - '@oro_locale.manager.localization'
        tags:
            - { name: kernel.cache_warmer }
