services:
    _defaults:
        public: false

    Oro\Bundle\LocaleBundle\Command\OroLocalizationDumpCommand:
        arguments:
            - '@oro_locale.settings'
            - '@filesystem'
            - '%kernel.project_dir%'
        tags:
            - { name: console.command }

    Oro\Bundle\LocaleBundle\Command\UpdateLocalizationCommand:
        arguments:
            - '@doctrine'
        tags:
            - { name: console.command }
