css:
    inputs:
        # Variables
        - 'bundles/orosidebar/css/scss/variables/variables.scss'

        # Styles
        - 'bundles/orosidebar/css/scss/main.scss'
        - 'bundles/orosidebar/sidebar_widgets/sticky_note/css/styles.css'
