system_configuration:
    groups:
        tag_settings:
            title:       oro.tag.system_configuration.groups.tag_settings.title
    fields:
        oro_tag.taxonomy_colors:
            data_type: array
            type: Oro\Bundle\FormBundle\Form\Type\OroColorTableType
            options:
                label: oro.tag.system_configuration.fields.taxonomy.label
    tree:
        system_configuration:
            platform:
                children:
                    general_setup:
                        children:
                            look_and_feel:
                                children:
                                    tag_settings:
                                        children:
                                            - oro_tag.taxonomy_colors
