services:
    oro_microsoft_integration.form.type.microsoft_imap_redirect_url:
        class: Oro\Bundle\MicrosoftIntegrationBundle\Form\Type\UrlInfoType
        arguments:
            - '@router'
        tags:
            - { name: form.type }
