services:
    _defaults:
        public: true

    Oro\Bundle\UserBundle\Controller\ConfigurationController:
        calls:
            - ['setContainer', ['@Psr\Container\ContainerInterface']]
        tags:
            - { name: container.service_subscriber }
            - { name: container.service_subscriber, id: 'oro_config.user' }

    Oro\Bundle\UserBundle\Controller\SecurityController:
        calls:
            - ['setContainer', ['@Psr\Container\ContainerInterface']]
        tags:
            - { name: container.service_subscriber }
