services:
    _defaults:
        public: true

    Oro\Bundle\EntityMergeBundle\Controller\MergeController:
        calls:
            - ['setContainer', ['@Psr\Container\ContainerInterface']]
        tags:
            - { name: container.service_subscriber }
