services:
    Oro\Bundle\ImportExportBundle\Command\ImportCommand:
        public: false
        class: Oro\Bundle\ImportExportBundle\Command\ImportCommand
        arguments:
            - '@oro_importexport.processor.registry'
            - '@akeneo_batch.connectors'
            - '@oro_message_queue.client.message_producer'
            - '@oro_importexport.file.file_manager'
            - '@oro_user.manager'
        tags:
            - { name: console.command }

    Oro\Bundle\ImportExportBundle\Command\Cron\CleanupStorageCommand:
        public: false
        arguments:
            - '@oro_importexport.file.file_manager'
            - '@oro_importexport.manager.import_export_result_manager'
        tags:
            - { name: console.command }
