styles:
    inputs:
        # Settings
        - 'bundles/oroui/css/scss/settings/global-settings.scss'

        # Styles
        - '~slick-carousel/slick/slick.scss'
        - 'bundles/oroui/css/scss/oro/loading/loading-bar.scss'
        - 'bundles/oroui/css/scss/font-awesome/core.scss'
        - 'bundles/oroviewswitcher/view-switcher/scss/styles.scss'
    output: 'css/view-switcher.css'
