<?php

return [
    \Symfony\Bundle\FrameworkBundle\FrameworkBundle::class => ['all' => true],
    \Sensio\Bundle\FrameworkExtraBundle\SensioFrameworkExtraBundle::class => ['all' => true],
    \Symfony\Bundle\TwigBundle\TwigBundle::class => ['all' => true],
    \Symfony\Bundle\WebProfilerBundle\WebProfilerBundle::class => ['dev' => true, 'test' => true],
    \Symfony\Bundle\MonologBundle\MonologBundle::class => ['all' => true],
    \Symfony\Bundle\DebugBundle\DebugBundle::class => ['dev' => true],
    \Symfony\Bundle\MakerBundle\MakerBundle::class => ['dev' => true],
    \Doctrine\Bundle\DoctrineBundle\DoctrineBundle::class => ['all' => true],
    \Doctrine\Bundle\MigrationsBundle\DoctrineMigrationsBundle::class => ['all' => true],
    \Symfony\Bundle\SecurityBundle\SecurityBundle::class => ['all' => true],
    \Twig\Extra\TwigExtraBundle\TwigExtraBundle::class => ['all' => true],
    \Symfony\WebpackEncoreBundle\WebpackEncoreBundle::class => ['all' => true],
    \Doctrine\Bundle\FixturesBundle\DoctrineFixturesBundle::class => ['dev' => true, 'test' => true],
    \Liip\FunctionalTestBundle\LiipFunctionalTestBundle::class => ['dev' => true, 'test' => true],
    \Lexik\Bundle\JWTAuthenticationBundle\LexikJWTAuthenticationBundle::class => ['all' => true],
    \EasyCorp\Bundle\EasyAdminBundle\EasyAdminBundle::class => ['all' => true],
    \Stof\DoctrineExtensionsBundle\StofDoctrineExtensionsBundle::class => ['all' => true],
    \Scheb\TwoFactorBundle\SchebTwoFactorBundle::class => ['all' => true],
    \OldSound\RabbitMqBundle\OldSoundRabbitMqBundle::class => ['all' => true],
    \DAMA\DoctrineTestBundle\DAMADoctrineTestBundle::class => ['dev' => true, 'test' => true],
    \FriendsOfBehat\SymfonyExtension\Bundle\FriendsOfBehatSymfonyExtensionBundle::class => ['test' => true],

    /**
     * Oro Bundles listing, All these bundles are static as
     * opposed to any of the above bundles
     */

    \Oro\Bundle\ActionBundle\OroActionBundle::class => ['all' => true],
    \Oro\Bundle\ActivityBundle\OroActivityBundle::class  => ['all' => true],
    \Oro\Bundle\ActivityListBundle\Model\Accessor\ActivityAccessor::class  => ['all' => true],
    \Oro\Bundle\AddressBundle\OroAddressBundle::class  => ['all' => true],
    \Oro\Bundle\ApiBundle\OroApiBundle::class  => ['all' => true],
    \Oro\Bundle\AssetBundle\OroAssetBundle::class => ['all' => true],
    \Oro\Bundle\AttachmentBundle\OroAttachmentBundle::class => ['all' => true],
    \Oro\Bundle\BatchBundle\OroBatchBundle::class => ['all' => true],
    \Oro\Bundle\BusinessEntitiesBundle\OroBusinessEntitiesBundle::class => ['all' => true],
    \Oro\Bundle\CacheBundle\OroCacheBundle::class => ['all' => true],
    \Oro\Bundle\ChartBundle\OroChartBundle::class => ['all' => true],
    \Oro\Bundle\CommentBundle\OroCommentBundle::class => ['all' => true],
    \Oro\Bundle\ConfigBundle\OroConfigBundle::class => ['all' => true],
    \Oro\Bundle\CurrencyBundle\OroCurrencyBundle::class => ['all' => true],
    \Oro\Bundle\DashboardBundle\OroDashboardBundle::class => ['all' => true],
    \Oro\Bundle\DataGridBundle\OroDataGridBundle::class => ['all' => true],
    \Oro\Bundle\DataAuditBundle\OroDataAuditBundle::class => ['all' => true],
    \Oro\Bundle\DigitalAssetBundle\OroDigitalAssetBundle::class => ['all' => true],
    \Oro\Bundle\DistributionBundle\OroDistributionBundle::class => ['all' => true],
    \Oro\Bundle\DraftBundle\OroDraftBundle::class => ['all' => true],
    \Oro\Bundle\EmailBundle\OroEmailBundle::class => ['all' => true],
    \Oro\Bundle\EmbeddedFormBundle\OroEmbeddedFormBundle::class => ['all' => true],
    \Oro\Bundle\EntityBundle\OroEntityBundle::class => ['all' => true],
    \Oro\Bundle\EntityConfigBundle\OroEntityConfigBundle::class => ['all' => true],
    \Oro\Bundle\EntityExtendBundle\OroEntityExtendBundle::class => ['all' => true],
    \Oro\Bundle\EntityMergeBundle\OroEntityMergeBundle::class => ['all' => true],
    \Oro\Bundle\EntityPaginationBundle\OroEntityPaginationBundle::class => ['all' => true],
    \Oro\Bundle\FeatureToggleBundle\OroFeatureToggleBundle::class => ['all' => true],
    \Oro\Bundle\FilterBundle\OroFilterBundle::class => ['all' => true],
    \Oro\Bundle\FormBundle\OroFormBundle::class => ['all' => true],
    \Oro\Bundle\GaufretteBundle\OroGaufretteBundle::class  => ['all' => true],
    \Oro\Bundle\GoogleIntegrationBundle\OroGoogleIntegrationBundle::class => ['all' => true],
    \Oro\Bundle\HelpBundle\OroHelpBundle::class  => ['all' => true],
    \Oro\Bundle\ImapBundle\OroImapBundle::class => ['all' => true],
    \Oro\Bundle\ImportExportBundle\OroImportExportBundle::class  => ['all' => true],
    \Oro\Bundle\InstallerBundle\OroInstallerBundle::class  => ['all' => true],
    \Oro\Bundle\IntegrationBundle\OroIntegrationBundle::class  => ['all' => true],
    \Oro\Bundle\LayoutBundle\OroLayoutBundle::class  => ['all' => true],
    \Oro\Bundle\LocaleBundle\OroLocaleBundle::class  => ['all' => true],
    \Oro\Bundle\LoggerBundle\OroLoggerBundle::class  => ['all' => true],
    \Oro\Bundle\MessageQueueBundle\OroMessageQueueBundle::class  => ['all' => true],
    \Oro\Bundle\MicrosoftIntegrationBundle\OroMicrosoftIntegrationBundle::class  => ['all' => true],
    \Oro\Bundle\MigrationBundle\OroMigrationBundle::class  => ['all' => true],
    \Oro\Bundle\NavigationBundle\OroNavigationBundle::class  => ['all' => true],
    \Oro\Bundle\NoteBundle\OroNoteBundle::class  => ['all' => true],
    \Oro\Bundle\NotificationBundle\OroNotificationBundle::class  => ['all' => true],
    \Oro\Bundle\OrganizationBundle\OroOrganizationBundle::class  => ['all' => true],
    \Oro\Bundle\PlatformBundle\OroPlatformBundle::class  => ['all' => true],
    \Oro\Bundle\QueryDesignerBundle\OroQueryDesignerBundle::class  => ['all' => true],
    \Oro\Bundle\ReminderBundle\OroReminderBundle::class  => ['all' => true],
    \Oro\Bundle\ReportBundle\OroReportBundle::class  => ['all' => true],
    \Oro\Bundle\ScopeBundle\OroScopeBundle::class  => ['all' => true],
    \Oro\Bundle\SearchBundle\OroSearchBundle::class  => ['all' => true],
    \Oro\Bundle\SecurityBundle\OroSecurityBundle::class  => ['all' => true],
    \Oro\Bundle\SegmentBundle\OroSegmentBundle::class  => ['all' => true],
    \Oro\Bundle\SidebarBundle\OroSidebarBundle::class  => ['all' => true],
    \Oro\Bundle\SoapBundle\OroSoapBundle::class  => ['all' => true],
    \Oro\Bundle\SSOBundle\OroSSOBundle::class  => ['all' => true],
    \Oro\Bundle\SyncBundle\OroSyncBundle::class  => ['all' => true],
    \Oro\Bundle\TagBundle\OroTagBundle::class  => ['all' => true],
    \Oro\Bundle\TestFrameworkBundle\OroTestFrameworkBundle::class  => ['all' => true],
    \Oro\Bundle\TestGeneratorBundle\OroTestGeneratorBundle::class  => ['all' => true],
    \Oro\Bundle\ThemeBundle\OroThemeBundle::class  => ['all' => true],
    \Oro\Bundle\TranslationBundle\OroTranslationBundle::class  => ['all' => true],
    \Oro\Bundle\UIBundle\OroUIBundle::class  => ['all' => true],
    \Oro\Bundle\UserBundle\OroUserBundle::class  => ['all' => true],
    \Oro\Bundle\ViewSwitcherBundle\OroViewSwitcherBundle::class  => ['all' => true],
    \Oro\Bundle\WindowsBundle\OroWindowsBundle::class  => ['all' => true],
    \Oro\Bundle\WorkflowBundle\OroWorkflowBundle::class  => ['all' => true],
    \Oro\Bundle\WsseAuthenticationBundle\OroWsseAuthenticationBundle::class  => ['all' => true],
];