entity_config:
    entity:
        entity:
            form:
                block_config:
                    general:
                        title:              oro.entity_config.block_titles.general.label
                        priority:           100
                    associations:
                        title:              oro.entity_config.block_titles.associations.label
                        priority:           50
                    other:
                        title:              oro.entity_config.block_titles.other.label
                        priority:           -255

            items:
                icon:
                    options:
                        priority:           10
                    form:
                        type:               Oro\Bundle\FormBundle\Form\Type\OroIconType
                        options:
                            label:          oro.entity.entity_config.entity.entity.items.icon
                            block:          general
                            required:       false
                label:
                    options:
                        translatable:       true
                        priority:           20
                    constraints:
                        - NotBlank:         ~
                        - Length:
                            min:            2
                            max:            50
                    grid:
                        type:               html
                        label:              oro.entity.entity_config.entity.entity.items.label
                        required:           true
                        template:           OroEntityConfigBundle:Config:propertyLabel.html.twig
                    form:
                        type:               Symfony\Component\Form\Extension\Core\Type\TextType
                        options:
                            label:          oro.entity.entity_config.entity.entity.items.label
                            block:          general
                            required:       true
                            strip_tags:     true

                plural_label:
                    options:
                        translatable:       true
                        priority:           35
                    constraints:
                        - NotBlank:         ~
                        - Length:
                            min:            2
                            max:            50
                    form:
                        type:               Symfony\Component\Form\Extension\Core\Type\TextType
                        options:
                            label:          oro.entity.entity_config.entity.entity.items.plural_label
                            block:          general
                            required:       true
                            strip_tags:     true

                description:
                    options:
                        translatable:       true
                        priority:           50
                    constraints:
                        - Length:
                            max:            500
                    form:
                        type:               Symfony\Component\Form\Extension\Core\Type\TextareaType
                        options:
                            label:          oro.entity.entity_config.entity.entity.items.description
                            block:          general
                            required:       false
                            strip_tags:     true
        field:
            form:
                block_config:
                    general:
                        title:              oro.entity_config.block_titles.general.label
                        priority:           100
                    other:
                        title:              oro.entity_config.block_titles.other.label
                        priority:           -255

            items:
                label:
                    options:
                        translatable:       true
                        priority:           10
                    constraints:
                        - NotBlank:         ~
                        - Length:
                            min:            2
                            max:            50
                    grid:
                        type:               html
                        label:              oro.entity.entity_config.entity.field.items.label
                        required:           true
                        template:           OroEntityConfigBundle:Config:propertyLabel.html.twig
                        sortable:           true
                    form:
                        type:               Symfony\Component\Form\Extension\Core\Type\TextType
                        options:
                            label:          oro.entity.entity_config.entity.field.items.label
                            tooltip:        oro.entity.entity_config.entity.field.items.label.tooltip
                            block:          general
                            required:       true
                            strip_tags:     true

                description:
                    options:
                        translatable:       true
                        priority:           30
                    constraints:
                        - Length:
                            max:            500
                    form:
                        type:               Symfony\Component\Form\Extension\Core\Type\TextareaType
                        options:
                            label:          oro.entity.entity_config.entity.field.items.description
                            tooltip:        oro.entity.entity_config.entity.field.items.description.tooltip
                            block:          general
                            required:       false
                            strip_tags:     true

    datagrid:
        field:
            items:
                is_visible:
                    options:
                        require_schema_update: true
                        value_type:         integer
                        default_value:      1
                        allowed_type:       [string, integer, smallint, bigint, boolean, datetime, date, time, float, decimal, money, percent, enum, multiEnum, manyToOne, oneToOne]
                        required_property:
                            config_id:
                                scope:      extend
                            code:           owner
                            value:          Custom
                    form:
                        type:               Oro\Bundle\EntityExtendBundle\Form\Type\ChoiceType
                        options:
                            choices:
                                No: 0
                                oro.entity.entity_config.datagrid.field.items.is_visible.shown: 1
                                oro.entity.entity_config.datagrid.field.items.is_visible.hidden: 3
                                oro.entity.entity_config.datagrid.field.items.is_visible.mandatory: 2
                            placeholder:    false
                            block:          other
                            label:          oro.entity.entity_config.datagrid.field.items.is_visible
                            tooltip:        oro.entity.entity_config.datagrid.field.items.is_visible.tooltip

                show_filter:
                    options:
                        value_type:         boolean
                        allowed_type:       [string, integer, smallint, bigint, boolean, datetime, date, time, float, decimal, money, percent, enum, multiEnum, manyToOne, oneToOne]
                        required_property:
                            config_id:
                                scope:      extend
                            code:           owner
                            value:          Custom
                    form:
                        type:               Symfony\Component\Form\Extension\Core\Type\ChoiceType
                        options:
                            choices:
                                No:         0
                                Yes:        1
                            placeholder:    false
                            block:          other
                            label:          oro.entity.entity_config.datagrid.field.items.show_filter
                order:
                    options:
                        value_type:         integer
                        required_property:
                            config_id:
                                scope:      extend
                            code:           owner
                            value:          Custom
                    form:
                        type:               Symfony\Component\Form\Extension\Core\Type\IntegerType
                        options:
                            block:          other
                            label:          oro.entity.entity_config.datagrid.field.items.order
                            required:       false

    form:
        entity:
            items:
                # form type for specific entity
                form_type:
                    options: []
                # form options for specific entity
                form_options:
                    options:
                        auditable: false
        field:
            items:
                # form type for specific field
                form_type:
                    options: []
                # form options for specific field
                form_options:
                    options:
                        auditable: false
                # is form enabled for specific field
                is_enabled:
                    options:
                        value_type:         boolean
                        default_value:      true
                        required_property:
                            config_id:
                                scope:      extend
                            code:           owner
                            value:          Custom

                    form:
                        type:               Symfony\Component\Form\Extension\Core\Type\ChoiceType
                        options:
                            choices:
                                No:         0
                                Yes:        1
                            placeholder:    false
                            block:          other
                            label:          oro.entity.entity_config.form.field.items.is_enabled

    view:
        field:
            items:
                is_displayable:
                    options:
                        value_type:         boolean
                        default_value:      true
                        required_property:
                            config_id:
                                scope:      extend
                            code:           owner
                            value:          Custom

                    form:
                        type:               Symfony\Component\Form\Extension\Core\Type\ChoiceType
                        options:
                            choices:
                                No:         0
                                Yes:        1
                            placeholder:    false
                            block:          other
                            label:          oro.entity.entity_config.view.field.items.is_displayable
                priority:
                    options:
                        value_type:         integer
                        required_property:
                            config_id:
                                scope:      extend
                            code:           owner
                            value:          Custom
                    form:
                        type:               Symfony\Component\Form\Extension\Core\Type\IntegerType
                        options:
                            block:          other
                            label:          oro.entity.entity_config.view.field.items.priority
                            required:       false

    grouping:
        entity:
            items:
                # it allows to group entities. An entity can be included in several groups
                groups: # array of strings
                    options: []

    dictionary:
        entity:
            items:
                # specify the list of fields for which the virtual fields can be created
                # if not specified the virtual fields are created for all fields, except identifier ones
                virtual_fields: # array of strings
                    options:
                        auditable: false
                # specify the list of fields used for searching in the reports filter
                search_fields: # array of strings
                    options:
                        auditable: false
                # specify representation field used for rendering titles for search items in the reports filter
                representation_field: # string
                    options:
                        auditable: false
    fallback:
        entity:
            items: ~
