css:
    inputs:
        # Variables
        - 'bundles/oroattachment/css/scss/variables/variables.scss'
        - 'bundles/oroattachment/css/scss/variables/mobile-variables.scss'

        # Styles
        - 'bundles/oroattachment/css/scss/main.scss'
