system_configuration:
    groups:
        attachment_settings:
            icon:   fa-file
            title:  oro.attachment.config.attachment.label
        attachment_mime_types_settings:
            title:  oro.attachment.config.mime_types.label
        attachment_file_size_settings:
            title:  oro.attachment.config.file_size_settings.label
        attachment_processors_settings:
            title:  oro.attachment.config.attachment_processors_settings.label
            description: oro.attachment.config.attachment_processors_settings.description
            description_style: warning
    fields:
        oro_attachment.maxsize:
            data_type: integer
            type: Symfony\Component\Form\Extension\Core\Type\IntegerType
            options:
                required: true
                label: oro.attachment.config.file_size.label
                empty_data: 1
                tooltip: oro.attachment.max_size.tooltip
                constraints:
                    - NotBlank: ~
                    - Type: integer
                    - Range:
                        min: 1
                        max: 2047 # in bytes equivalents to ~2147483647 which max allowed value for fileSize column of File entity

        oro_attachment.upload_file_mime_types:
            data_type: string
            type: Oro\Bundle\AttachmentBundle\Form\Type\FileMimeTypeConfigType
            options:
                label: oro.attachment.config.upload_file_mime_types.label
                tooltip: oro.attachment.config.upload_file_mime_types.tooltip
                constraints:
                    - Oro\Bundle\AttachmentBundle\Validator\Constraints\MimeType: { type: file }

        oro_attachment.upload_image_mime_types:
            data_type: string
            type: Oro\Bundle\AttachmentBundle\Form\Type\ImageMimeTypeConfigType
            options:
                label: oro.attachment.config.upload_image_mime_types.label
                tooltip: oro.attachment.config.upload_image_mime_types.tooltip
                constraints:
                    - Oro\Bundle\AttachmentBundle\Validator\Constraints\MimeType: { type: image }

        oro_attachment.processors_allowed:
            data_type: boolean
            type: Oro\Bundle\ConfigBundle\Form\Type\ConfigCheckbox
            page_reload: true
            options:
                label: oro.attachment.config.feature.attachment_processors_allowed.label
                tooltip: oro.attachment.config.feature.attachment_processors_allowed.tooltip
                resettable: true

        oro_attachment.jpeg_quality:
            data_type: integer
            type: Symfony\Component\Form\Extension\Core\Type\IntegerType
            options:
                required: true
                label: oro.attachment.config.jpeg_quality
                tooltip: oro.attachment.config.quality_tooltip
                constraints:
                    - NotBlank: ~
                    - Type: integer
                    - Range:
                          min: 30
                          max: 100

        oro_attachment.png_quality:
            data_type: integer
            type: Symfony\Component\Form\Extension\Core\Type\ChoiceType
            search_type: choice
            options:
                label: oro.attachment.config.png_quality
                tooltip: oro.attachment.config.quality_tooltip
                required: true
                constraints:
                    - NotBlank: ~
                choices:
                    oro.attachment.config.png_preserve_quality: 100
                    oro.attachment.config.png_minimize_file_size: 35

    tree:
        system_configuration:
            platform:
                children:
                    general_setup:
                        children:
                            attachment_settings:
                                priority: -10
                                children:
                                    attachment_file_size_settings:
                                        children:
                                            - oro_attachment.maxsize
                                    attachment_mime_types_settings:
                                        children:
                                            - oro_attachment.upload_file_mime_types
                                            - oro_attachment.upload_image_mime_types
                                    attachment_processors_settings:
                                        children:
                                            - oro_attachment.processors_allowed
                                            - oro_attachment.jpeg_quality
                                            - oro_attachment.png_quality

    api_tree:
        attachments:
            oro_attachment.upload_file_mime_types: ~
            oro_attachment.upload_image_mime_types: ~
