system_configuration:
    groups:
        google_settings:
            handler: '@oro_imap.form.google_imap_config_handler::handle'
        google_imap_settings:
            title: oro.imap.system_configuration.groups.google_imap_settings.title
        microsoft_settings:
            handler: '@oro_imap.form.microsoft_imap_config_handler::handle'
        microsoft_imap_settings:
            title: oro.imap.system_configuration.groups.microsoft_imap_settings.title

    fields:
        oro_imap.enable_google_imap:
            data_type: boolean
            type: Oro\Bundle\ImapBundle\Form\Type\GoogleSyncConfigCheckbox
            options:
                label: oro.imap.system_configuration.fields.enable_google_imap.label
                tooltip: oro.imap.system_configuration.fields.enable_google_imap.tooltip
                required: false
                resettable: false
            priority: 10
        oro_imap.enable_microsoft_imap:
            data_type: boolean
            type: Oro\Bundle\ImapBundle\Form\Type\MicrosoftSyncConfigCheckboxType
            options:
                label: oro.imap.system_configuration.fields.enable_microsoft_imap.label
                tooltip: oro.imap.system_configuration.fields.enable_microsoft_imap.tooltip
                required: false
                resettable: false
    tree:
        system_configuration:
            platform:
                children:
                    integrations:
                        children:
                            google_settings:
                                children:
                                    google_imap_settings:
                                        children:
                                            - oro_imap.enable_google_imap
                            microsoft_settings:
                                children:
                                    microsoft_imap_settings:
                                        children:
                                            - oro_imap.enable_microsoft_imap
